<a href="https://colab.research.google.com/github/mehraj-alom/pytorch/blob/main/pytorch_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Start

In [98]:
!nvidia-smi #System mangement inference

/bin/bash: line 1: nvidia-smi: command not found


In [99]:
import torch
torch.__version__

'2.6.0+cu124'

## Tensors

In [100]:
#scaler
scaler = torch.tensor(7)
print(scaler)
print(scaler.ndim)
print(scaler.item())

tensor(7)
0
7


In [101]:
#Vector
vector = torch.tensor([7,9])
vector,vector.ndim,vector.shape

(tensor([7, 9]), 1, torch.Size([2]))

In [102]:
#Matrix
Matrix = torch.tensor([[2,3],
                       [3,6]])
Matrix,Matrix.ndim,Matrix.shape,Matrix[1]

(tensor([[2, 3],
         [3, 6]]),
 2,
 torch.Size([2, 2]),
 tensor([3, 6]))

In [103]:
#TENSOR
Tensor = torch.tensor([[[2,3,4],
                        [5,6,7],
                        [7,8,0]],
                       ])
Tensor,Tensor.ndim,Tensor.shape
# -->  torch.Size([1, 3, 3])) means 1 tensor of size 3 by 3

(tensor([[[2, 3, 4],
          [5, 6, 7],
          [7, 8, 0]]]),
 3,
 torch.Size([1, 3, 3]))

In [104]:
#TENSOR
Tensor = torch.tensor([[[2,3,4],
                        [5,6,7],
                        [7,8,0]],
                       [[2,3,4],
                        [5,6,7],
                        [7,8,0]]])
Tensor,Tensor.ndim,Tensor.shape
#  -->  torch.Size([2, 3, 3])) means 2 tensor of size 3 by 3

(tensor([[[2, 3, 4],
          [5, 6, 7],
          [7, 8, 0]],
 
         [[2, 3, 4],
          [5, 6, 7],
          [7, 8, 0]]]),
 3,
 torch.Size([2, 3, 3]))

## Random Tensors
# WHY ??
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data


` Start With random number -> Look at data -> Update Random Numbbers -> look at data ............`

In [105]:
random_tensors = torch.rand(2,3,4)
random_tensors,random_tensors.ndim

(tensor([[[0.3901, 0.9088, 0.5334, 0.7073],
          [0.7116, 0.2050, 0.3078, 0.9809],
          [0.0103, 0.4660, 0.4604, 0.8547]],
 
         [[0.4525, 0.6317, 0.4760, 0.2200],
          [0.2166, 0.2571, 0.0458, 0.1755],
          [0.6177, 0.8291, 0.5246, 0.2708]]]),
 3)

In [106]:
#Random tensor Similer to image shape
Random_tens = torch.rand(size=(3,224,224))
Random_tens,Random_tens.shape,Random_tens.ndim

(tensor([[[0.7197, 0.3081, 0.3892,  ..., 0.8298, 0.9454, 0.8039],
          [0.3937, 0.2775, 0.6415,  ..., 0.9636, 0.6473, 0.8856],
          [0.1048, 0.7677, 0.8854,  ..., 0.5910, 0.1396, 0.4820],
          ...,
          [0.0689, 0.9215, 0.4849,  ..., 0.5814, 0.8598, 0.6564],
          [0.3493, 0.0643, 0.4134,  ..., 0.1466, 0.1036, 0.4578],
          [0.9760, 0.8793, 0.1022,  ..., 0.2884, 0.8731, 0.2955]],
 
         [[0.4231, 0.4808, 0.4522,  ..., 0.5762, 0.7849, 0.0746],
          [0.1512, 0.2537, 0.8303,  ..., 0.5044, 0.5205, 0.9193],
          [0.7402, 0.1169, 0.9328,  ..., 0.0697, 0.6136, 0.4005],
          ...,
          [0.4531, 0.3057, 0.8446,  ..., 0.0906, 0.9781, 0.2339],
          [0.5199, 0.4462, 0.5111,  ..., 0.0788, 0.1127, 0.2211],
          [0.7822, 0.1611, 0.9133,  ..., 0.2139, 0.1390, 0.0475]],
 
         [[0.5663, 0.2418, 0.7390,  ..., 0.9055, 0.8579, 0.9039],
          [0.0983, 0.3548, 0.0504,  ..., 0.4605, 0.2840, 0.6555],
          [0.2710, 0.9154, 0.7390,  ...,

In [107]:
# Tensor Zeros and ones
ones = torch.ones(size=(2, 2))
zeros = torch.zeros(size=(2,3))
print("Tensor of ones:")
print(ones)
print("\nTensor of zeros:")
print(zeros)
print(ones.dtype)
print(zeros.dtype)

Tensor of ones:
tensor([[1., 1.],
        [1., 1.]])

Tensor of zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.float32
torch.float32


In [108]:
# Tensor Range
tensor_range = torch.arange(start=0,step =67 ,end=1000)
tensor_range,tensor_range.shape

(tensor([  0,  67, 134, 201, 268, 335, 402, 469, 536, 603, 670, 737, 804, 871,
         938]),
 torch.Size([15]))

In [109]:
#Creating Tensors Like
ten_zeros = torch.zeros_like(input=tensor_range)
ten_zeros,ten_zeros.shape

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), torch.Size([15]))

## Tensor Data Types

In [110]:
tensor_dType = torch.tensor([[2.0,3],
                             [2,8]],
                            dtype=torch.float16,
                            device=None,
                            requires_grad=False) #To track gradients with this operation
tensor_dType.dtype

torch.float16

In [111]:
#Data Type Conversion
int_32_tensor = tensor_dType.type(torch.int32)
int_32_tensor,int_32_tensor.dtype

(tensor([[2, 3],
         [2, 8]], dtype=torch.int32),
 torch.int32)

In [112]:
tensor_dType * int_32_tensor

tensor([[ 4.,  9.],
        [ 4., 64.]], dtype=torch.float16)

In [113]:
tensor_dType.device

device(type='cpu')

In [114]:
tensor_dType = tensor_dType.type(torch.int32)

In [115]:
#Tensor inbuilt operation
print(torch.mul(tensor_dType,int_32_tensor))
print(torch.div(tensor_dType,int_32_tensor))
print(torch.add(tensor_dType,int_32_tensor))
print(torch.matmul(tensor_dType,int_32_tensor))

tensor([[ 4,  9],
        [ 4, 64]], dtype=torch.int32)
tensor([[1., 1.],
        [1., 1.]])
tensor([[ 4,  6],
        [ 4, 16]], dtype=torch.int32)
tensor([[10, 30],
        [20, 70]], dtype=torch.int32)


In [116]:
a = torch.rand(3,4)
b = torch.rand(3,4)
c = torch.matmul(a.T,b) # Transpose to match the inner shape
c

tensor([[0.7969, 0.9090, 1.0515, 0.4683],
        [0.5505, 0.6490, 0.7616, 0.3516],
        [0.1604, 0.4909, 0.3284, 0.3250],
        [0.1276, 0.4782, 0.2843, 0.3195]])

## Tensor aggregation

In [117]:
torch.min(c),torch.max(c),torch.mean(c),torch.sum(c)

(tensor(0.1276), tensor(1.0515), tensor(0.5033), tensor(8.0529))

## Argmin & Argmax (Positional MAX And MIN)

In [118]:
print(torch.argmax(tensor_dType))
print(tensor_dType.argmax())
print("********")
print(torch.argmin(tensor_dType))
print(tensor_dType.argmin())

tensor(3)
tensor(3)
********
tensor(0)
tensor(0)


## Reshping , Viewing and Stacking  sqeezing and unsquezing Tensors
 * Reshaping:
     Changes the shape of an input tensor to a defined shape.
 * View:
   Returns a view of an input tensor with a certain shape, sharing the same memory as the original tensor.
 * Stacking:
   Combines multiple tensors either vertically (vstack) or horizontally
   (hstack).
 * Squeeze:
  Removes all dimensions of size 1 from a tensor.
 * Unsqueeze:
  Adds a dimension of size 1 to a target tensor at a specified position.
 * Permute:
  Returns a view of the input with its dimensions permuted or swapped in a specific way.

In [119]:
x = torch.arange(0,18,dtype=torch.float16)
print(x)
x_reshaped = x.reshape(3,6) # Shape must be compitable with the original tensor , otherwise it will show an error
print(x_reshaped)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17.], dtype=torch.float16)
tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.],
        [12., 13., 14., 15., 16., 17.]], dtype=torch.float16)


In [120]:
z = x.view(2,9)
print(z)
z[:,0] = 2
z,x # Z sharing the same memory as the original tensor x

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12., 13., 14., 15., 16., 17.]], dtype=torch.float16)


(tensor([[ 2.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
         [ 2., 10., 11., 12., 13., 14., 15., 16., 17.]], dtype=torch.float16),
 tensor([ 2.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  2., 10., 11., 12., 13.,
         14., 15., 16., 17.], dtype=torch.float16))

In [121]:
# Stacking the tensors
## stacked1 = torch.stack([x,z],dim=0)  --> sharing the same memory as the original tensor.
stacked = torch.stack([x,x,x],dim=1)
print(stacked,"\n")
        # OR
torch.vstack([x,x,x]),torch.hstack([x,x,x])


tensor([[ 2.,  2.,  2.],
        [ 1.,  1.,  1.],
        [ 2.,  2.,  2.],
        [ 3.,  3.,  3.],
        [ 4.,  4.,  4.],
        [ 5.,  5.,  5.],
        [ 6.,  6.,  6.],
        [ 7.,  7.,  7.],
        [ 8.,  8.,  8.],
        [ 2.,  2.,  2.],
        [10., 10., 10.],
        [11., 11., 11.],
        [12., 12., 12.],
        [13., 13., 13.],
        [14., 14., 14.],
        [15., 15., 15.],
        [16., 16., 16.],
        [17., 17., 17.]], dtype=torch.float16) 



(tensor([[ 2.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  2., 10., 11., 12., 13.,
          14., 15., 16., 17.],
         [ 2.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  2., 10., 11., 12., 13.,
          14., 15., 16., 17.],
         [ 2.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  2., 10., 11., 12., 13.,
          14., 15., 16., 17.]], dtype=torch.float16),
 tensor([ 2.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  2., 10., 11., 12., 13.,
         14., 15., 16., 17.,  2.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  2.,
         10., 11., 12., 13., 14., 15., 16., 17.,  2.,  1.,  2.,  3.,  4.,  5.,
          6.,  7.,  8.,  2., 10., 11., 12., 13., 14., 15., 16., 17.],
        dtype=torch.float16))

In [122]:
x = torch.zeros(1,10)
print(x.shape)
torch.squeeze(x).shape   #Removes all dimensions of size 1 from a tensor.

torch.Size([1, 10])


torch.Size([10])

In [123]:
print(torch.unsqueeze(x,dim=1))
print(torch.unsqueeze(x,dim=1).shape)  #Adds a dimension of size 1 to a target tensor at a specified position.

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])
torch.Size([1, 1, 10])


In [124]:
z = torch.rand(2,1,10)
print(z,"\n",z.shape)
# Permute the dimensions of z. Since z has shape [2,1,10], we need a tuple of 3 dimensions for permute.
# For example, to swap the dimensions, we can use (1,2, 0)
print(torch.permute(z,dims=(1,2,0)))

tensor([[[0.8935, 0.5641, 0.8185, 0.8929, 0.1142, 0.7162, 0.0621, 0.1934,
          0.0560, 0.6124]],

        [[0.9843, 0.2519, 0.6722, 0.4822, 0.7418, 0.5410, 0.0794, 0.4796,
          0.5262, 0.6794]]]) 
 torch.Size([2, 1, 10])
tensor([[[0.8935, 0.9843],
         [0.5641, 0.2519],
         [0.8185, 0.6722],
         [0.8929, 0.4822],
         [0.1142, 0.7418],
         [0.7162, 0.5410],
         [0.0621, 0.0794],
         [0.1934, 0.4796],
         [0.0560, 0.5262],
         [0.6124, 0.6794]]])


## Tensor Indexing

In [125]:
# Create a tensor of random integers
y = torch.randint(low=0, high=1000, size=(2,2,10), dtype=torch.int32)
print("Original tensor:")
print(y)

# Change the value at y[0,0]
y[0,0,0] = 99999
print("\nTensor after changing y[0,0]:")
print(y)
print("permuted")
print(torch.permute(y,dims=(1,2,0)))
y[0][0][5] = 20087567
y

Original tensor:
tensor([[[957, 318, 347, 886, 922, 579, 141, 722, 240, 628],
         [395, 378, 650, 289, 345, 531, 266, 350, 631, 127]],

        [[397, 160, 562, 126, 776, 111, 703,   2, 769, 409],
         [740, 944,   7, 665, 815, 219,  20, 786, 460, 648]]],
       dtype=torch.int32)

Tensor after changing y[0,0]:
tensor([[[99999,   318,   347,   886,   922,   579,   141,   722,   240,   628],
         [  395,   378,   650,   289,   345,   531,   266,   350,   631,   127]],

        [[  397,   160,   562,   126,   776,   111,   703,     2,   769,   409],
         [  740,   944,     7,   665,   815,   219,    20,   786,   460,   648]]],
       dtype=torch.int32)
permuted
tensor([[[99999,   397],
         [  318,   160],
         [  347,   562],
         [  886,   126],
         [  922,   776],
         [  579,   111],
         [  141,   703],
         [  722,     2],
         [  240,   769],
         [  628,   409]],

        [[  395,   740],
         [  378,   944],
         [  6

tensor([[[   99999,      318,      347,      886,      922, 20087567,      141,
               722,      240,      628],
         [     395,      378,      650,      289,      345,      531,      266,
               350,      631,      127]],

        [[     397,      160,      562,      126,      776,      111,      703,
                 2,      769,      409],
         [     740,      944,        7,      665,      815,      219,       20,
               786,      460,      648]]], dtype=torch.int32)

## Pytorch tensors to numpy
 * `Np ndarray to tensors` -> `torch.from_numpy(ndarray)`
 * `tensor to nparray ` -> `torch.Tensor.numpy()`

In [126]:
import numpy as np
a = np.random.randint(1,100,20).astype(np.int16)
print(a)
print(a.dtype)

b = torch.from_numpy(a)
print(b.dtype)

c = torch.Tensor.numpy(b)
print(c.dtype)

[23 58 33 73 28 80 58 15 11 77 12 80 21 19 74 64  4 11 62 81]
int16
torch.int16
int16


## Pytorch Reproducibility (TAKING THE RANDOM OUT OF RANDOM)

In [127]:
RANDOM_SEED = 2
torch.manual_seed(RANDOM_SEED)
tensor_x = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
tensor_y = torch.rand(3,4) ## Random seed works for one line or one seed
print(tensor_x == tensor_y)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## WAYS OF ACCESSING A GPU IN PYTORCH
* Running tensors and Pytorch objects on the GPUs(for faster computation)

* Use colab gpu or have your own , else you can use cloud computing AWS, GCP etc

In [129]:
torch.cuda.is_available()

False

In [135]:
## Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu" ##best practice
device
torch.cuda.device_count()

0

## Setup Device agnostic code and putting tensors on and off GPU
 * Putting tensors and models on the gpu for Faster computations

In [138]:
## Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu" ##best practice
print(device)
print(torch.cuda.device_count())

tensor_a = torch.tensor([1,2,3,4,5,6,7],device=device)
print(tensor_a,tensor_a.device)
# on_gpu = tensor_a.to("cuda")
# on_gpu

cpu
0
tensor([1, 2, 3, 4, 5, 6, 7]) cpu
