<a href="https://colab.research.google.com/github/mehraj-alom/pytorch/blob/main/pytorch_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi #System mangement inference

Wed Aug 13 21:22:19 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   68C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
torch.__version__

'2.6.0+cu124'

## Tensors

In [4]:
#scaler
scaler = torch.tensor(7)
print(scaler)
print(scaler.ndim)
print(scaler.item())

tensor(7)
0
7


In [10]:
#Vector
vector = torch.tensor([7,9])
vector,vector.ndim,vector.shape

(tensor([7, 9]), 1, torch.Size([2]))

In [16]:
#Matrix
Matrix = torch.tensor([[2,3],
                       [3,6]])
Matrix,Matrix.ndim,Matrix.shape,Matrix[1]

(tensor([[2, 3],
         [3, 6]]),
 2,
 torch.Size([2, 2]),
 tensor([3, 6]))

In [20]:
#TENSOR
Tensor = torch.tensor([[[2,3,4],
                        [5,6,7],
                        [7,8,0]],
                       ])
Tensor,Tensor.ndim,Tensor.shape
# -->  torch.Size([1, 3, 3])) means 1 tensor of size 3 by 3

(tensor([[[2, 3, 4],
          [5, 6, 7],
          [7, 8, 0]]]),
 3,
 torch.Size([1, 3, 3]))

In [22]:
#TENSOR
Tensor = torch.tensor([[[2,3,4],
                        [5,6,7],
                        [7,8,0]],
                       [[2,3,4],
                        [5,6,7],
                        [7,8,0]]])
Tensor,Tensor.ndim,Tensor.shape
#  -->  torch.Size([2, 3, 3])) means 2 tensor of size 3 by 3

(tensor([[[2, 3, 4],
          [5, 6, 7],
          [7, 8, 0]],
 
         [[2, 3, 4],
          [5, 6, 7],
          [7, 8, 0]]]),
 3,
 torch.Size([2, 3, 3]))

## Random Tensors
# WHY ??
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data


` Start With random number -> Look at data -> Update Random Numbbers -> look at data ............`

In [28]:
random_tensors = torch.rand(2,3,4)
random_tensors,random_tensors.ndim

(tensor([[[0.9859, 0.8428, 0.3475, 0.6307],
          [0.7614, 0.7806, 0.8362, 0.5400],
          [0.0995, 0.4244, 0.9420, 0.3306]],
 
         [[0.3946, 0.4040, 0.9767, 0.8511],
          [0.6461, 0.2052, 0.8966, 0.6889],
          [0.3432, 0.5887, 0.5065, 0.0720]]]),
 3)

In [31]:
#Random tensor Similer to image shape
Random_tens = torch.rand(size=(3,224,224))
Random_tens,Random_tens.shape,Random_tens.ndim

(tensor([[[6.8111e-01, 3.4705e-01, 8.0316e-01,  ..., 3.9764e-01,
           6.9543e-01, 4.4234e-01],
          [1.2789e-01, 8.8615e-01, 3.8306e-01,  ..., 5.5647e-01,
           9.6229e-01, 6.7543e-01],
          [3.7648e-01, 5.3423e-01, 3.8123e-01,  ..., 1.8131e-01,
           2.7696e-01, 4.5281e-01],
          ...,
          [2.8109e-01, 7.6454e-01, 9.0677e-01,  ..., 5.3495e-01,
           5.1374e-01, 9.3259e-01],
          [7.5555e-01, 4.6906e-01, 9.3056e-01,  ..., 5.8629e-01,
           4.7308e-01, 6.7749e-01],
          [2.5307e-01, 8.6256e-01, 5.7581e-01,  ..., 1.2404e-01,
           1.5435e-03, 8.0227e-02]],
 
         [[4.6366e-01, 5.3290e-01, 1.6945e-01,  ..., 8.9817e-01,
           8.5738e-01, 9.2314e-01],
          [1.7751e-01, 2.4543e-01, 2.9726e-01,  ..., 3.1693e-01,
           1.6579e-01, 5.5784e-01],
          [3.0026e-01, 7.6741e-02, 4.8500e-01,  ..., 8.1103e-01,
           5.9360e-01, 5.9780e-02],
          ...,
          [2.7536e-02, 4.9530e-01, 7.3496e-01,  ..., 2.941

In [41]:
# Tensor Zeros and ones
ones = torch.ones(size=(2, 2))
zeros = torch.zeros(size=(2,3))
print("Tensor of ones:")
print(ones)
print("\nTensor of zeros:")
print(zeros)
print(ones.dtype)
print(zeros.dtype)

Tensor of ones:
tensor([[1., 1.],
        [1., 1.]])

Tensor of zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.float32
torch.float32


In [48]:
# Tensor Range
tensor_range = torch.arange(start=0,step =67 ,end=1000)
tensor_range,tensor_range.shape

(tensor([  0,  67, 134, 201, 268, 335, 402, 469, 536, 603, 670, 737, 804, 871,
         938]),
 torch.Size([15]))

In [51]:
#Creating Tensors Like
ten_zeros = torch.zeros_like(input=tensor_range)
ten_zeros,ten_zeros.shape

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), torch.Size([15]))

## Tensor Data Types

In [52]:
#Time stamp 1:58 hour